



CREATE TABLE GER082_TREINAMENTO (
    CODIGO_EMPRESA            INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL             INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_TREINAMENTO        INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    DESCRICAO_TREINAMENTO     VC120 /* VC120 = VARCHAR(120) */,
    VERSAO_TREINAMENTO        VC060 /* VC060 = VARCHAR(60) */,
    CARGAHORARIA_TREINAMENTO  VC060 /* VC060 = VARCHAR(60) */,
    CONTEUDO_TREINAMENTO      VC600 /* VC600 = VARCHAR(600) */,
    SITUACAO_TREINAMENTO      VC020 /* VC020 = VARCHAR(20) */
);



ALTER TABLE GER082_TREINAMENTO ADD CONSTRAINT GER082_PK PRIMARY KEY (CODIGO_EMPRESA, CODIGO_FILIAL, CODIGO_TREINAMENTO);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE GER082_TREINAMENTO ADD CONSTRAINT GER082_FK01 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL) REFERENCES GER021A_FILIAL (CODIGO_EMPRESA, CODIGO_FILIAL);

