



CREATE TABLE GER020M_PESSOACARGO (
    CODIGO_EMPRESA      INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL       INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    NUMERO_SEQUENCIA    INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_PESSOA       INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_CARGO        INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    DATA_PESSOACARGO    DATA /* DATA = DATE */,
    USRINC_PESSOACARGO  VC025 /* VC025 = VARCHAR(25) */
);



ALTER TABLE GER020M_PESSOACARGO ADD CONSTRAINT GER020M_PK PRIMARY KEY (CODIGO_EMPRESA, CODIGO_FILIAL, NUMERO_SEQUENCIA, CODIGO_PESSOA, CODIGO_CARGO);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE GER020M_PESSOACARGO ADD CONSTRAINT GER020M_FK01 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL) REFERENCES GER021A_FILIAL (CODIGO_EMPRESA, CODIGO_FILIAL);
ALTER TABLE GER020M_PESSOACARGO ADD CONSTRAINT GER020M_FK02 FOREIGN KEY (CODIGO_PESSOA) REFERENCES GER020_PESSOA (CODIGO_PESSOA);
ALTER TABLE GER020M_PESSOACARGO ADD CONSTRAINT GER020M_FK03 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL, CODIGO_CARGO) REFERENCES GER080_CARGO (CODIGO_EMPRESA, CODIGO_FILIAL, CODIGO_CARGO);
