



CREATE TABLE GER082A_TREINAMENTOPESSOA (
    CODIGO_EMPRESA                 INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL                  INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    NUMERO_SEQUENCIA               INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_TREINAMENTO             INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_PESSOA                  INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    SITUACAO_TREINAMENTOPESSOA     VC040 /* VC040 = VARCHAR(60) */,
    DTFINALIZA_TREINAMENTOPESSOA   DATA /* DATA = DATE */,
    USRFINALIZA_TREINAMENTOPESSOA  VC025 /* VC025 = VARCHAR(25) */,
    DTINC_TREINAMENTOPESSOA        DATA /* DATA = DATE */,
    USRINC_TREINAMENTOPESSOA       VC025 /* VC025 = VARCHAR(25) */
);





ALTER TABLE GER082A_TREINAMENTOPESSOA ADD CONSTRAINT GER082A_PK PRIMARY KEY (CODIGO_EMPRESA, CODIGO_FILIAL, NUMERO_SEQUENCIA, CODIGO_PESSOA, CODIGO_TREINAMENTO);

/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE GER082A_TREINAMENTOPESSOA ADD CONSTRAINT GER082A_FK01 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL) REFERENCES GER021A_FILIAL (CODIGO_EMPRESA, CODIGO_FILIAL);
ALTER TABLE GER082A_TREINAMENTOPESSOA ADD CONSTRAINT GER082A_FK02 FOREIGN KEY (CODIGO_PESSOA) REFERENCES GER020_PESSOA (CODIGO_PESSOA);
ALTER TABLE GER082A_TREINAMENTOPESSOA ADD CONSTRAINT GER082A_FK03 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL, CODIGO_TREINAMENTO) REFERENCES GER082_TREINAMENTO (CODIGO_EMPRESA, CODIGO_FILIAL, CODIGO_TREINAMENTO);

