


CREATE TABLE GER020N_SGQAUDITORIA (
    CODIGO_EMPRESA                 INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL                  INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_SGQAUDITORIA            INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    DTINCLUSAO_SGQAUDITORIA        DATA /* DATA = DATE */,
    DTINICIO_SGQAUDITORIA          DATA /* DATA = DATE */,
    DTFINAL_SGQAUDITORIA           DATA /* DATA = DATE */,
    CODIGO_PESSOA                  INTEIRO /* INTEIRO = INTEGER */,
    OBSERVACAO_SGQAUDITORIA        VC600 /* VC600 = VARCHAR(600) */,
    INFOPROCESSO_SGQAUDITORIA      VC240 /* VC240 = VARCHAR(240) */,
    INFOREQNORMATIVO_SGQAUDITORIA  VC240 /* VC240 = VARCHAR(240) */,
    CODIGO_RESPONSAVEL             INTEIRO /* INTEIRO = INTEGER */,
    DATA_SGQAUDITORIA              DATA /* DATA = DATE */,
    HORA_SGQAUDITORIA              HORA /* HORA = TIME */,
    SITUACAO_SGQAUDITORIA          VC030 /* VC030 = VARCHAR(30) */
);




ALTER TABLE GER020N_SGQAUDITORIA ADD CONSTRAINT GER020N_PK PRIMARY KEY (CODIGO_EMPRESA, CODIGO_FILIAL, CODIGO_SGQAUDITORIA);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE GER020N_SGQAUDITORIA ADD CONSTRAINT GER020N_FK01 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL) REFERENCES GER021A_FILIAL (CODIGO_EMPRESA, CODIGO_FILIAL);
ALTER TABLE GER020N_SGQAUDITORIA ADD CONSTRAINT GER020N_FK02 FOREIGN KEY (CODIGO_PESSOA) REFERENCES GER020_PESSOA (CODIGO_PESSOA);
ALTER TABLE GER020N_SGQAUDITORIA ADD CONSTRAINT GER020N_FK03 FOREIGN KEY (CODIGO_RESPONSAVEL) REFERENCES GER020_PESSOA (CODIGO_PESSOA);
