


CREATE TABLE GER20NA_ESCOPO (
    CODIGO_EMPRESA           INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL            INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_ESCOPO            INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_SGQAUDITORIA      INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    DESCRICAO_ESCOPO         VC200 /* VC200 = VARCHAR(200) */,
    CODIGO_RESPONSAVEL       INTEIRO /* INTEIRO = INTEGER */,
    INFOPROCESSO_ESCOPO      VC240 /* VC240 = VARCHAR(240) */,
    INFOREQNORMATIVO_ESCOPO  VC240 /* VC240 = VARCHAR(240) */,
    DATA_ESCOPO              DATA /* DATA = DATE */,
    HORA_ESCOPO              HORA /* HORA = TIME */
);



ALTER TABLE GER20NA_ESCOPO ADD CONSTRAINT GER20NA_PK PRIMARY KEY (CODIGO_EMPRESA, CODIGO_FILIAL, CODIGO_ESCOPO, CODIGO_SGQAUDITORIA);

/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE GER20NA_ESCOPO ADD CONSTRAINT GER020NA_FK03 FOREIGN KEY (CODIGO_RESPONSAVEL) REFERENCES GER020_PESSOA (CODIGO_PESSOA);
ALTER TABLE GER20NA_ESCOPO ADD CONSTRAINT GER20NA_FK01 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL) REFERENCES GER021A_FILIAL (CODIGO_EMPRESA, CODIGO_FILIAL);
ALTER TABLE GER20NA_ESCOPO ADD CONSTRAINT GER20NA_FK02 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL, CODIGO_SGQAUDITORIA) REFERENCES GER020N_SGQAUDITORIA (CODIGO_EMPRESA, CODIGO_FILIAL, CODIGO_SGQAUDITORIA);

