




CREATE TABLE CPR003D_HISTFINALIDADE (
    NUMERO_SEQUENCIA          INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_EMPRESA            INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL             INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    NUMERO_ORDEMCOMPRA        INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    DTALTERA_HISTFINALIDADE   DATA /* DATA = DATE */,
    HRALTERA_HISTFINALIDADE   HORA /* HORA = TIME */,
    USRALTERA_HISTFINALIDADE  VC025 /* VC025 = VARCHAR(25) */,
    ANTFINALIDADE_MATERIAL    VC040 /* VC040 = VARCHAR(60) */,
    ATUALFINALIDADE_MATERIAL  VC040 /* VC040 = VARCHAR(60) */,
    INFO_HISTFINALIDADE       VC400 /* VC400 = VARCHAR(400) */
);




ALTER TABLE CPR003D_HISTFINALIDADE ADD CONSTRAINT CPR003D_PK PRIMARY KEY (NUMERO_SEQUENCIA, CODIGO_EMPRESA, CODIGO_FILIAL, NUMERO_ORDEMCOMPRA);


ALTER TABLE CPR003D_HISTFINALIDADE ADD CONSTRAINT CPR003D_FK02 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL, NUMERO_ORDEMCOMPRA) REFERENCES CPR003_ORDEMCOMPRA (CODIGO_EMPRESA, CODIGO_FILIAL, NUMERO_ORDEMCOMPRA);
ALTER TABLE CPR003D_HISTFINALIDADE ADD CONSTRAINT FK_CPR003DFK01 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL) REFERENCES GER021A_FILIAL (CODIGO_EMPRESA, CODIGO_FILIAL);


