


CREATE TABLE GER021E_HISTSITUACAO (
    NUMERO_SEQUENCIA            INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_EMPRESA              INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL               INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    DTALTERA_HISTSITUACAO       DATA /* DATA = DATE */,
    HRALTERA_HISTSITUACAO       HORA /* HORA = TIME */,
    USRALTERA_HISTSITUACAO      VC025 /* VC025 = VARCHAR(25) */,
    ANTSITUACAO_HISTSITUACAO    VC040 /* VC040 = VARCHAR(60) */,
    ATUALSITUACAO_HISTSITUACAO  VC040 /* VC040 = VARCHAR(60) */,
    INFO_HISTSITUACAO           VC400 /* VC400 = VARCHAR(400) */
);



ALTER TABLE GER021E_HISTSITUACAO ADD CONSTRAINT GER021E_PK PRIMARY KEY (NUMERO_SEQUENCIA, CODIGO_EMPRESA, CODIGO_FILIAL);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE GER021E_HISTSITUACAO ADD CONSTRAINT GER021E_FK01 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL) REFERENCES GER021A_FILIAL (CODIGO_EMPRESA, CODIGO_FILIAL);

