



CREATE TABLE SGQ001A_EVIDENCIA (
    CODIGO_EVIDENCIA     INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_ACAO          INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_EMPRESA       INTEIRO NOT NULL/* INTEIRO = INTEGER */,
    CODIGO_FILIAL        INTEIRO NOT NULL/* INTEIRO = INTEGER */,
    DESCRICAO_EVIDENCIA  VC450 /* VC450 = VARCHAR(450) */
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE SGQ001A_EVIDENCIA ADD CONSTRAINT SGQ001A_PK PRIMARY KEY (CODIGO_EVIDENCIA, CODIGO_ACAO, CODIGO_EMPRESA, CODIGO_FILIAL);



ALTER TABLE SGQ001A_EVIDENCIA ADD CONSTRAINT SGQ001A_FK01 FOREIGN KEY (CODIGO_ACAO, CODIGO_EMPRESA, CODIGO_FILIAL) REFERENCES SGQ001_ACAO (CODIGO_ACAO, CODIGO_EMPRESA, CODIGO_FILIAL);


