



CREATE TABLE SGQ001C_CORRECAO (
    CODIGO_CORRECAO     INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_ACAO         INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_EMPRESA      INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL       INTEIRO NOT NULL/* INTEIRO = INTEGER */,
    CODIGO_PESSOA       INTEIRO /* INTEIRO = INTEGER */,
    DESCRICAO_CORRECAO  VC450 /* VC450 = VARCHAR(450) */
);

ALTER TABLE SGQ001C_CORRECAO ADD CONSTRAINT SGQ001C_PK PRIMARY KEY (CODIGO_CORRECAO, CODIGO_ACAO, CODIGO_EMPRESA, CODIGO_FILIAL);



ALTER TABLE SGQ001C_CORRECAO ADD CONSTRAINT SGQ001C_FK01 FOREIGN KEY (CODIGO_ACAO, CODIGO_EMPRESA, CODIGO_FILIAL) REFERENCES SGQ001_ACAO (CODIGO_ACAO, CODIGO_EMPRESA, CODIGO_FILIAL);
ALTER TABLE SGQ001C_CORRECAO ADD CONSTRAINT SGQ001C_FK02 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL) REFERENCES GER021A_FILIAL (CODIGO_EMPRESA, CODIGO_FILIAL);
ALTER TABLE SGQ001C_CORRECAO ADD CONSTRAINT SGQ001C_FK03 FOREIGN KEY (CODIGO_PESSOA) REFERENCES GER020_PESSOA (CODIGO_PESSOA);

