


CREATE TABLE SGQ001G_ANALISECRITICA (
    CODIGO_ANALISECRITICA     INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_ACAO               INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_EMPRESA            INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL             INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_PESSOA             INTEIRO /* INTEIRO = INTEGER */,
    DESCRICAO_ANALISECRITICA  VC450 /* VC450 = VARCHAR(450) */
);
