



CREATE TABLE SGQ002_CRONOGRAMA (
    CODIGO_CRONOGRAMA          INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_EMPRESA             INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL              INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_PESSOA              INTEIRO /* INTEIRO = INTEGER */,
    CODIGO_OBRA                INTEIRO /* INTEIRO = INTEGER */,
    DTINIPREVISTO_CRONOGRAMA   DATA /* DATA = DATE */,
    DTTERMPREVISTO_CRONOGRAMA  DATA /* DATA = DATE */,
    DTINIREAL_CRONOGRAMA       DATA /* DATA = DATE */,
    DTTERMREAL_CRONOGRAMA      DATA /* DATA = DATE */,
    VLRPREVISTO_CRONOGRAMA     MOEDA /* MOEDA = NUMERIC(15,4) */,
    VLRREALIZADO_CRONOGRAMA    MOEDA /* MOEDA = NUMERIC(15,4) */,
    OBSERVACAO_CRONOGRAMA      VC600 /* VC600 = VARCHAR(600) */,
    ATIVIDADE_CRONOGRAMA       VC400 /* VC400 = VARCHAR(400) */,
    DATA_CRONOGRAMA            DATA /* DATA = DATE */,
    USRINCLUI_CRONOGRAMA       VC025 /* VC025 = VARCHAR(25) */,
    SITUACAO_CRONOGRAMA        VC025 /* VC025 = VARCHAR(25) */
);





ALTER TABLE SGQ002_CRONOGRAMA ADD CONSTRAINT SGQ002_PK PRIMARY KEY (CODIGO_CRONOGRAMA, CODIGO_EMPRESA, CODIGO_FILIAL);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE SGQ002_CRONOGRAMA ADD CONSTRAINT SGQ002_FK01 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL) REFERENCES GER021A_FILIAL (CODIGO_EMPRESA, CODIGO_FILIAL);
ALTER TABLE SGQ002_CRONOGRAMA ADD CONSTRAINT SGQ002_FK02 FOREIGN KEY (CODIGO_PESSOA) REFERENCES GER020_PESSOA (CODIGO_PESSOA);
ALTER TABLE SGQ002_CRONOGRAMA ADD CONSTRAINT SGQ002_FK03 FOREIGN KEY (CODIGO_EMPRESA, CODIGO_FILIAL, CODIGO_OBRA) REFERENCES ENG004_OBRA (CODIGO_EMPRESA, CODIGO_FILIAL, CODIGO_OBRA);
