

CREATE TABLE SGQ004A_CRITERIOAVALIACAO (
    CODIGO_CRITERIOAVALIACAO      INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_CONFIGAVALIACAOFORNEC  INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_EMPRESA                INTEIRO /* INTEIRO = INTEGER */,
    CODIGO_FILIAL                 INTEIRO /* INTEIRO = INTEGER */,
    INFO_CRITERIOAVALIACAO        VC100 /* VC100 = VARCHAR(100) */,
    USRINCLUI_CRITERIOAVALIACAO   VC025 /* VC025 = VARCHAR(25) */,
    DESCRICAO_CRITERIOAVALIACAO   VC100 /* VC100 = VARCHAR(100) */
);