



CREATE TABLE SGQ005_AVALIACAOFORNEC (
    CODIGO_AVALIACAOFORNEC      INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_EMPRESA              INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL               INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_PESSOA               INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    DATA_AVALIACAOFORNEC        DATA /* DATA = DATE */,
    USRINCLUI_AVALIACAOFORNEC   VC025 /* VC025 = VARCHAR(25) */,
    TIPO_AVALIACAOFORNEC        VC030 /* VC030 = VARCHAR(30) */,
    ROTINA_ORIGEM               VC025 /* VC025 = VARCHAR(25) */,
    NUMERO_ORIGEM               INTEIRO /* INTEIRO = INTEGER */,
    OBSERVACAO_AVALIACAOFORNEC  VC400 /* VC400 = VARCHAR(400) */,
    VLRMEDIA_AVALIACAOFORNEC    MOEDA /* MOEDA = NUMERIC(15,4) */,
    RESULTADO_AVALIACAOFORNEC   VC060 /* VC060 = VARCHAR(60) */
);