



CREATE TABLE SGQ005A_ITEMAVALIADO (
    CODIGO_ITEMAVALIADO           INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_CONFIGAVALIACAOFORNEC  INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_EMPRESA                INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    CODIGO_FILIAL                 INTEIRO NOT NULL /* INTEIRO = INTEGER */,
    DESCRICAO_ITEMAVALIADO        VC100 /* VC100 = VARCHAR(100) */,
    NOTA_ITEMAVALIADO             MOEDA /* MOEDA = NUMERIC(15,4) */,
    INFOAVALAICAO_ITEMAVALIADO    VC030 /* VC030 = VARCHAR(30) */,
    DTAVALIACAO_ITEMAVALIADO      DATA /* DATA = DATE */,
    USRAVAL__ITEMAVALIADO         VC025 /* VC025 = VARCHAR(25) */
);
