CREATE TABLE TEST_USER (ID INT, NAME VARCHAR(50));

INSERT INTO TEST_USER VALUES (1, 'Admin');

SET TERM ˆ ;

CREATE PROCEDURE SP_TEST AS
BEGIN
    UPDATE TEST_USER SET NAME = 'Tested'`;
ENDˆ

SET TERM ; ˆ

DELETE FROM TEST_USER WHERE ID = 99;